# Generated by Django 5.0.2 on 2024-02-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0003_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Description', models.TextField(max_length=250)),
                ('Author', models.CharField(max_length=20)),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
